GL_TRUE: int
GL_FALSE: int
GL_COLOR_BUFFER_BIT: int

def glViewport(x: int, y: int, width: int, height: int) -> None: ...
def glClearColor(r: int, g: int, b: int, a: int) -> None: ...
def glClear(mask: int) -> None: ...
