def create_context() -> None: ...
def new_frame() -> None: ...
def render() -> None: ...
def get_draw_data() -> int: ...  # TODO verify
def begin(name: str) -> None: ...
def text(text: str) -> None: ...
def button(text: str) -> bool: ...
def end() -> None: ...
