"""Stub file for the pyglm.glm module."""

from ctypes import c_voidp
from typing import TypeVar, overload

class _GLMType: ...

class vec2(_GLMType):
    x: float
    y: float

class vec3(_GLMType):
    x: float
    y: float
    z: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    @overload
    def __init__(self, position: tuple[float, float, float]) -> None: ...
    def __setitem__(self, index: int, value: float) -> None: ...

class vec4(_GLMType):
    x: float
    y: float
    z: float
    w: float

class mat2(_GLMType): ...
class mat3(_GLMType): ...

class mat4(_GLMType):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...

class mat2x3(_GLMType): ...
class mat3x2(_GLMType): ...
class mat2x4(_GLMType): ...
class mat4x2(_GLMType): ...
class mat3x4(_GLMType): ...
class mat4x3(_GLMType): ...

_T = TypeVar("_T")

def radians(degrees: float) -> float: ...
def rotate(matrix: mat4, angle: float, axis: vec3) -> mat4: ...
def translate(matrix: mat4, vector: vec3) -> mat4: ...
def perspective(fov: float, aspect: float, near: float, far: float) -> mat4: ...
def value_ptr(matrix: _GLMType) -> c_voidp: ...
