import ctypes
from OpenGL.GL.shaders import ShaderProgram
import numpy as np

GL_TRUE: int
GL_FALSE: int
GL_COLOR_BUFFER_BIT: int
GL_ARRAY_BUFFER: int
GL_STATIC_DRAW: int
GL_FLOAT: int
GL_UNSIGNED_INT: int
GL_TRIANGLES: int
GL_FRAGMENT_SHADER: int
GL_VERTEX_SHADER: int

def glViewport(x: int, y: int, width: int, height: int) -> None: ...
def glClearColor(r: int, g: int, b: int, a: int) -> None: ...
def glClear(mask: int) -> None: ...
def glGenBuffers(size: int) -> int: ...  # TODO verify
def glBindBuffer(target: int, buffer: int) -> None: ...
def glBufferData(
    target: int, size: int, data: np.ndarray | None, usage: int
) -> None: ...
def glBufferSubData(
    target: int, offset: int, size: int, data: np.ndarray | None
) -> None: ...
def glDeleteBuffers(size: int, buffers: list[int]) -> None: ...
def glFlush() -> None: ...
def glEnableVertexAttribArray(index: int) -> None: ...
def glDisableVertexAttribArray(index: int) -> None: ...
def glVertexAttribPointer(
    index: int,
    size: int,
    type: int,
    normalized: bool,
    stride: int,
    pointer: ctypes.c_voidp,
) -> None: ...
def glVertexAttribDivisor(index: int, divisor: int) -> None: ...
def glDrawArraysInstanced(
    mode: int, first: int, count: int, instancecount: int
) -> None: ...
def glUseProgram(program: ShaderProgram) -> None: ...
