import ctypes

import numpy as np
from OpenGL.GL.shaders import ShaderProgram

GL_TRUE: int
GL_FALSE: int
GL_COLOR_BUFFER_BIT: int
GL_DEPTH_BUFFER_BIT: int
GL_DEPTH_CLAMP: int
GL_ARRAY_BUFFER: int
GL_STATIC_DRAW: int
GL_FLOAT: int
GL_UNSIGNED_INT: int
GL_TRIANGLES: int
GL_FRAGMENT_SHADER: int
GL_VERTEX_SHADER: int
GL_DEPTH_TEST: int
GL_LESS: int
GL_CULL_FACE: int
GL_BACK: int
GL_TEXTURE_2D_ARRAY: int
GL_TEXTURE_MIN_FILTER: int
GL_LINEAR_MIPMAP_LINEAR: int
GL_TEXTURE_MAG_FILTER: int
GL_NEAREST: int
GL_TEXTURE_WRAP_S: int
GL_TEXTURE_WRAP_T: int
GL_REPEAT: int
GL_RGBA8: int
GL_RGBA: int
GL_UNSIGNED_BYTE: int

def glViewport(x: int, y: int, width: int, height: int) -> None: ...
def glClearColor(r: int, g: int, b: int, a: int) -> None: ...
def glClear(mask: int) -> None: ...
def glGenBuffers(size: int) -> int: ...  # TODO verify
def glBindBuffer(target: int, buffer: int) -> None: ...
def glBufferData(
    target: int, size: int, data: np.ndarray | None, usage: int
) -> None: ...
def glBufferSubData(
    target: int, offset: int, size: int, data: np.ndarray | None
) -> None: ...
def glDeleteBuffers(size: int, buffers: list[int]) -> None: ...
def glFlush() -> None: ...
def glEnableVertexAttribArray(index: int) -> None: ...
def glDisableVertexAttribArray(index: int) -> None: ...
def glVertexAttribPointer(
    index: int,
    size: int,
    type: int,
    normalized: bool,
    stride: int,
    pointer: ctypes.c_voidp,
) -> None: ...
def glVertexAttribDivisor(index: int, divisor: int) -> None: ...
def glDrawArraysInstanced(
    mode: int, first: int, count: int, instancecount: int
) -> None: ...
def glGetUniformLocation(program: int, name: str) -> int: ...
def glUniform1i(location: int, v0: int) -> None: ...
def glUniform1f(location: int, v0: float) -> None: ...
def glUniform2f(location: int, v0: float, v1: float) -> None: ...
def glUniform3f(location: int, v0: float, v1: float, v2: float) -> None: ...
def glUniform4f(
    location: int, v0: float, v1: float, v2: float, v3: float
) -> None: ...
def glUniformMatrix2fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix3fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix4fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix2x3fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix3x2fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix2x4fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix4x2fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix3x4fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUniformMatrix4x3fv(
    location: int, count: int, transpose: int, value: ctypes.c_voidp
) -> None: ...
def glUseProgram(program: ShaderProgram) -> None: ...
def glEnable(cap: int) -> None: ...
def glDisable(cap: int) -> None: ...
def glDepthFunc(func: int) -> None: ...
def glCullFace(mode: int) -> None: ...
def glGenTextures(size: int) -> int: ...  # TODO verify
def glTexParameteri(target: int, pname: int, param: int) -> None: ...
def glTexImage3D(
    target: int,
    level: int,
    internalformat: int,
    width: int,
    height: int,
    depth: int,
    border: int,
    format: int,
    type: int,
    data: np.ndarray,
) -> None: ...
def glGenerateMipmap(target: int) -> None: ...
def glBindTexture(target: int, texture: int) -> None: ...
