class ShaderProgram(int): ...

def compileShader(source: str, mode: int) -> int: ...
def compileProgram(vertex: int, fragment: int) -> ShaderProgram: ...

class ShaderCompilationError(RuntimeError): ...
