SAMPLES: int
CONTEXT_VERSION_MAJOR: int
CONTEXT_VERSION_MINOR: int
OPENGL_FORWARD_COMPAT: int
OPENGL_PROFILE: int
OPENGL_CORE_PROFILE: int

type _GLFWwindowPointerT = int
type _GLFWmonitorPointerT = int

def init() -> bool: ...
def create_window(
    width: int,
    height: int,
    title: str,
    monitor: _GLFWwindowPointerT | None,
    share: _GLFWwindowPointerT | None,
) -> _GLFWwindowPointerT: ...
def terminate() -> None: ...
def make_context_current(window: _GLFWwindowPointerT) -> None: ...
def swap_interval(interval: int) -> None: ...
def swap_buffers(window: _GLFWwindowPointerT) -> None: ...
def poll_events() -> None: ...
def window_should_close(window: _GLFWwindowPointerT) -> bool: ...
def get_window_size(window: _GLFWwindowPointerT) -> tuple[int, int]: ...
def window_hint(hint: int, value: int) -> None: ...
